# Generated by Django 5.2.7 on 2026-02-15 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_assignment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.PositiveIntegerField(blank=True, help_text='Marks out of 10', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(upload_to='assignments/submissions/'),
        ),
    ]
