# Generated by Django 5.2.7 on 2026-02-15 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_submission_grade_remove_submission_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.enrollment'),
        ),
    ]
