# Generated by Django 5.2.7 on 2026-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_lessondownload_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='instructor_docs/'),
        ),
    ]
