# Generated by Django 5.2.7 on 2026-03-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_profile_verification_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
    ]
