# Generated by Django 5.2.7 on 2026-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_coursefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')]),
        ),
    ]
