# Generated by Django 5.2.7 on 2026-04-13 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Course duration (1–180 days)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
